# Generated by Django 5.1 on 2024-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBlogs', '0004_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ublog',
            name='Udate_of_post',
            field=models.DateField(auto_now_add=True),
        ),
    ]
